/*
 * STA 2E Unified Console - Species Ability list
 * ---------------------------------------------------------------
 * Keep this file in the same folder as STA2E_Unified_Console.html.
 * (It is a.js file instead of.json because browsers block pages
 * opened from a folder on your PC from reading.json files.)
 *
 * Each entry:  { "species": "...", "source": "...", "name": "...", "text": "" }
 *   species - groups the entry in the dropdown (taken from the book's TRAIT line)
 *   name    - shown in the dropdown and inserted into the box
 *   text    - optional rules text, inserted after the name. Left empty here:
 *             paste it from your own copy of the book if you want it inserted.
 *
 * Add entries by copying a line. Mind the commas between entries.
 * Sources: 2E Core Rulebook (14 species), Species Sourcebook (60 species).
 */
window.STA_SPECIES_ABILITIES = [
    {"species": "Aenar", "source": "Core Rulebook", "name": "Telepathic", "text": "Aenar can sense the minds of other living creatures in their vicinity, and can read the thoughts of others, though they have strict taboos about reading a mind without permission. See the Telepathy talent on page 156 for more details."},
    {"species": "Andorian", "source": "Core Rulebook", "name": "Intense", "text": "When you succeed at a task where you purchased one or more d20s by adding to Threat, you generate 1 bonus Momentum for each d20 purchased. Bonus Momentum may not be saved."},
    {"species": "Bajoran", "source": "Core Rulebook", "name": "The Will of the Prophets", "text": "You may find strength in the Prophets even when the situation is dire: once per adventure, when the gamemaster spends 3 or more Threat at once, you gain 1 Determination."},
    {"species": "Betazoid", "source": "Core Rulebook", "name": "Telepathic", "text": "Betazoids can sense the minds of living creatures in their vicinity and can read the thoughts and emotions of others. Each Betazoid has either Telepathy or Empathy (see page 155-page 156 for more details). Part-Betazoid characters generally have Empathy rather than Telepathy."},
    {"species": "Cardassian", "source": "Core Rulebook", "name": "Healthy Suspicions", "text": "You may add 1 Threat when interacting with an NPC to ask the gamemaster if that NPC is lying about something. The gamemaster must answer either Yes or No, and this answer must be accurate, but the gamemaster does not have to specify what the NPC is lying about."},
    {"species": "Denobulan", "source": "Core Rulebook", "name": "Breadth of Study", "text": "You may select two additional focuses. sslliiaatteeDD sseeiicceeppSS Hailing from the planet Denobula, Denobulans are a gregarious, inquisitive people who have been allies of humanity since the 2130s. Denobulans are long-lived and highly sociable, with large families—Denobulans are typically polyamorous, with individuals potentially having several spouses, each of whom may have several spouses of their own, and dozens of children between them—living in relatively close, communal environments. Culturally, Denobulans are an intellectually curious people, highly perceptive, and interested in a wide range of philosophies, with their long lives allowing them to pursue a wide range of fields of study, often granting them unusual perspectives on the different philosophies and fields of expertise they’ve studied."},
    {"species": "Ferengi", "source": "Core Rulebook", "name": "The Great Material Continuum", "text": "Once per session, when obtaining additional equipment, you may reduce the Opportunity Cost of an item by 1, to a minimum of 0."},
    {"species": "Human", "source": "Core Rulebook", "name": "Faith of the Heart", "text": "When you use one of your values to spend or gain Determination, you may also add 1 Momentum to the group pool."},
    {"species": "Klingon", "source": "Core Rulebook", "name": "Brak’lul", "text": "You gain 1 Protection which stacks with the benefits of any armor worn. Further, when another character attempts First Aid to heal you, they may re-roll a d20."},
    {"species": "Orion", "source": "Core Rulebook", "name": "Never at Face Value", "text": "Once per scene, you may add 1 Threat to ask the gamemaster a question about the situation, as if you had spent Momentum to Obtain Information."},
    {"species": "Romulan", "source": "Core Rulebook", "name": "Paranoia", "text": "When an action scene begins, if the gamemaster wishes an adversary to take the first turn, they must spend 1 Threat more than normal."},
    {"species": "Tellarite", "source": "Core Rulebook", "name": "Sturdy", "text": "You gain +1 Protection against Stun Attacks only. Further, when you suffer a complication that represents a physical hindrance or being stunned, dazed, or disoriented, you may take 1 Stress to ignore that complication (and remove any associated trait)."},
    {"species": "Trill", "source": "Core Rulebook", "name": "Patient", "text": "When you succeed at a task where you purchased one or more d20s by spending Momentum, you generate 1 bonus Momentum for each d20 purchased. Bonus Momentum may not be saved."},
    {"species": "Vulcan", "source": "Core Rulebook", "name": "Mental Discipline", "text": "While Vulcans have some psychic capabilities, they require training to use it effectively (see the Mind Meld talent, page 154). Further, your maximum Stress is based on your Control rather than your Fitness, and you may suffer 2 Stress to avoid suffering any trait that represents an emotional state. However, if you become Fatigued, you increase the Potency of any such emotion-related trait by 1."},
    {"species": "Android", "source": "Species Sourcebook", "name": "Synthetic Life-Form", "text": "You are not an organic being, and are not as vulnerable to physical harm: you have +1 Protection against Stun Attacks. You recover from injuries with Engineering tasks, rather than Medicine. In addition, you add 1 automatic success to any task roll which uses your Reason, due to your powerful positronic brain."},
    {"species": "Augment", "source": "Species Sourcebook", "name": "Genetically Enhanced", "text": "You are an Augment. You may select one or two talents which require the Augment trait, which you gain in addition to the normal talents you can select. If you select two of these Augment talents, then you must select an additional trait which represents a severe personality flaw or neurological problem, such as Heightened Aggression, or Sensory Processing Disorder."},
    {"species": "Aurelian", "source": "Species Sourcebook", "name": "Airborne Avian", "text": "Your powerful wings allow you to maneuver easily through the air. When you take a Movement minor action or Sprint major action, you may choose to fly; if you fly, you move one additional zone, and you ignore any difficult terrain or obstacles on the ground. However, weather conditions, such as strong winds, can act as difficult terrain when you fly. When in any enclosed space, including the interior of a starship, increase the complication range of all tasks you attempt by 2, as you feel agitated and claustrophobic."},
    {"species": "Aurelian", "source": "Species Sourcebook", "name": "Nimble Avian", "text": "Your agile body allows you to navigate your environment more efficiently. When you encounter difficult terrain during movement, you may reduce the Momentum cost of that terrain by 1. You may also reroll 1d20 on any Fitness + Conn task attempted when you take the Sprint major action."},
    {"species": "Barzan", "source": "Species Sourcebook", "name": "Unyielding Resolve", "text": "You give 100% as often as you are able, and you will not allow setbacks to deter you. When you spend a point of Determination on a task roll, if the task still fails, you regain that spent Determination."},
    {"species": "Benzite", "source": "Species Sourcebook", "name": "All Fingers and Thumbs", "text": "Your hands consist of four fingers and two thumbs each, and you’re used to operating technology swiftly and with precision. When you succeed at a task which would require extremely fine motor skills, you generate 1 bonus Momentum. Bonus Momentum cannot be saved."},
    {"species": "Betelgeusian", "source": "Species Sourcebook", "name": "Hardened for Battle", "text": "Your body is hardened against harm, and your mind is hardened against fear. You have +1 Protection against any ranged attack from a phaser, disruptor, or comparable energy weapon. In addition, whenever you would suffer a trait or other effect representing fear or panic, you may suffer 1 Stress to ignore that trait or effect."},
    {"species": "Orion", "source": "Species Sourcebook", "name": "Honor Among Thieves", "text": "When an ally attempts to lie, cheat, or steal from an enemy, you may spend 1 Momentum (Immediate) to assist that task roll automatically, by providing a lookout, or distracting the enemy, or otherwise trying to give your ally a better opportunity. Your assistance does not require you to take an action or prevent you doing anything else: you’re accustomed to covering your allies’ illicit ventures out of habit and reflex."},
    {"species": "Bolian", "source": "Species Sourcebook", "name": "Amiable", "text": "You’re outspoken and sociable, always with a supportive word to ease your comrades’ burdens. Whenever you succeed at a Presence-based task roll, the Momentum cost to remove an ally’s Stress is reduced to 1. Whenever you and an ally both rest, and spend a meaningful part of that rest together (the entire breather, at least half of a break, or at least one hour of a longer rest), you each recover 1 more Stress than normal."},
    {"species": "Borg", "source": "Species Sourcebook", "name": "Borg Implants", "text": "You are a Cyborg, and may select cybernetic talents. Further, you may select one, two, or three of the Borg implants from the sidebar on the next page. Medicine tasks performed on you increase their Difficulty by the number of implants you have chosen, as does the complication range of any tasks related to social interaction. You may remove an implant when you receive a milestone, in addition to any other changes you make to your character."},
    {"species": "Breen", "source": "Species Sourcebook", "name": "Gelatinous Form", "text": "In your natural gelatinous state, you may reroll 1d20 on any task roll using Control. You may assume a solid state by suffering 2 Stress, gaining 1 Protection, but losing the reroll from your gelatinous form. While wearing a refrigeration suit, you gain 1 Protection without the need to suffer Stress, and may remain in your gelatinous state."},
    {"species": "Brikar", "source": "Species Sourcebook", "name": "Rock Hard", "text": "Your body is huge, heavy, and rocky. You have 2 Protection against all attacks. However, you add 1 Threat whenever you take an action where your mass and size would be a potential risk."},
    {"species": "Bynar", "source": "Species Sourcebook", "name": "Bynar Pair", "text": "You are a Cyborg, and may select cybernetic talents. You always operate in a pair with another Bynar who has been with you since you were both children. Create a Bynar supporting character as your partner; this supporting character starts with one value, which must either be the same as one of yours, or directly reference it. You do not need to use Crew Support to introduce this supporting character each session, and they always accompany you (following the rules for uncontrolled supporting characters on page 144 of the core rulebook)."},
    {"species": "Caitian", "source": "Species Sourcebook", "name": "Feline Form", "text": "You have a prehensile tail, and retractable claws in your fingertips, useful for climbing and hunting. Whenever you attempt a task to maintain your balance or to climb, the first d20 you purchase is free. Further, you may grasp objects with your tail, though not as tightly or easily as with your hands. Due to your claws, your unarmed attacks may inflict both Stun and Deadly Injuries."},
    {"species": "Cetacean", "source": "Species Sourcebook", "name": "Aquatic Mammal", "text": "You can move freely and without hindrance through the water. You may ignore any traits or injuries caused by exposure to extremely cold aquatic conditions. However, when on land you are always considered to be Prone (core rulebook, page 288)."},
    {"species": "Chameloid", "source": "Species Sourcebook", "name": "Natural Shapeshifter", "text": "You commonly exist in a form other than your natural state. At the start of a mission, you gain an additional trait to reflect the form you’ve chosen, which may be the form of a specific individual. You may suffer 1 Stress as a minor action once per turn to change this form. It is difficult (requiring a successful Difficulty 3 task) to detect a disguised Chameloid without technological assistance."},
    {"species": "Changeling", "source": "Species Sourcebook", "name": "Morphogenic Matrix", "text": "You may suffer 1 Stress as a minor action once per turn to assume a different form, gaining one additional trait to reflect whatever form you have chosen. You cannot yet mimic a specific individual, and you must revert to a liquid state for a few hours after sixteen hours in a solid form. While in an alternate form, it is next to impossible (requiring a Difficulty 5 task roll) to detect a hidden Changeling. Your body is highly resistant to physical harm and energy weapons, giving you Protection 2, and your thoughts and emotions cannot be detected by telepaths or empaths. You are immune to extremes of heat, cold, and exposure to vacuum."},
    {"species": "Deltan", "source": "Species Sourcebook", "name": "Empath", "text": "You have the Empathy talent, described on page 155 of the core rulebook. You may develop this ability further by selecting the Telepathy talent during the course of character advancement."},
    {"species": "Edosian", "source": "Species Sourcebook", "name": "Trilateral Symmetry", "text": "Edosians are capable, with effort and practice, of compartmentalizing their thoughts and operating each arm completely independently, performing multiple complex tasks simultaneously. When you spend Momentum on the Swift Action option, you may suffer 1 Stress to ignore the normal Difficulty increase of your second action. You may also suffer 1 Stress to ignore the Difficulty increase from the Override starship conflict action."},
    {"species": "Efrosian", "source": "Species Sourcebook", "name": "Visual Spectrum", "text": "An Efrosian can see beyond the normal Human visual spectrum, from some infrared to ultraviolet light. Any task in which detecting those parts of the spectrum is useful reduce in Difficulty by 1. Location or situation traits such as low light levels, do not affect the Difficulty of tasks for an Efrosian."},
    {"species": "El-Aurian", "source": "Species Sourcebook", "name": "Transtemporal Awareness", "text": "You are aware of shifts and changes in the fabric of space-time in ways that few other beings are. Whenever there is a phenomenon present in a scene which was caused by alterations to the timeline, or the influence of alternate dimensions or extradimensional entities, the gamemaster must immediately inform you that something is wrong (though they do not have to specify what). You may add 1, 2, or 3 Threat to ask that many questions (as per Obtain Information) to try and discern details about the phenomenon."},
    {"species": "Exocomp", "source": "Species Sourcebook", "name": "Technological Life", "text": "You are not an organic being, and are not vulnerable to physical harm as they are: you have +1 Protection against Stun Attacks. You recover from injuries with Engineering, rather than Medicine. In addition, your onboard micro-replicator allows you to produce small tools and one-handed items for your own use with opportunity cost 1 by suffering 1 Stress for each such item created. Due to your lack of hands, you cannot use tools made for other creatures."},
    {"species": "Grazerite", "source": "Species Sourcebook", "name": "Agreeable", "text": "You are inclined to seek agreement and cooperation in everything you do."},
    {"species": "Hologram", "source": "Species Sourcebook", "name": "Photonic", "text": "You are not an organic being, and are not vulnerable to physical harm as they are: you have 2 Protection. Injuries and fatigue you suffer represent disruption to your holomatrix or damage to holo-emitters. You recover from injuries with Engineering tasks, rather than Medicine. You cannot be present in any scene where there are no holo-emitters. In addition, because you were programmed for a specific purpose, you do not have a pastime."},
    {"species": "Horta", "source": "Species Sourcebook", "name": "Silicon-Based Burrower", "text": "You are nigh-impervious to harm, having Protection 3, and you can move freely through solid rock with little difficulty (very dense rock might count as difficult terrain). Your acidic secretions give you a melee attack which inflicts Deadly 4 Injuries with the Debilitating and Piercing qualities."},
    {"species": "Illyrian", "source": "Species Sourcebook", "name": "Adapt and Excel", "text": "You may have the Augment trait. In addition, select a single attribute when you create your character: when you attempt a task using that attribute, you may suffer 1 Stress to reroll a single d20."},
    {"species": "Jem’Hadar", "source": "Species Sourcebook", "name": "Perfect Soldier", "text": "You are built for warfare. Your Unarmed Strike attacks may inflict Deadly Injuries, and have the Intense quality. Further, you have 1 Protection, and cannot suffer any Stun Injuries. However, you are uncomfortable among other species, and cannot easily empathize or relate to them, adding 1 Difficulty to any task rolls to interact with someone in a peaceful manner unless they are a direct Dominion superior. Finally, you require daily doses of ketracel-white to live: while you have your dose, you recover 4 Stress at the start of each scene, but you cannot rest normally, and each day you do not receive the white, you cannot recover Stress, and you gain the Withdrawal Symptoms trait."},
    {"species": "Kellerun", "source": "Species Sourcebook", "name": "Intense Defiance", "text": "Your people have endured fierce, brutal conflicts, and cultivated a defiant, pragmatic attitude towards hardship. When you suffer one or more Stress, you may add 1 to Threat to reduce the amount of Stress suffered by 1. Once per mission, when you become Fatigued, you may immediately add 2 Threat to recover 1 Stress."},
    {"species": "Kelpien", "source": "Species Sourcebook", "name": "Hunter or Prey", "text": "Your physiology is finely tuned to evading pursuit or running down a quarry. When you take the Movement minor action, reduce the Momentum cost of crossing difficult terrain by 1. When you take the Sprint major action, you move one additional zone. In addition, you gain a benefit depending on whether you are pre- or post-Vahar’ai."},
    {"species": "Klingon Quchha’", "source": "Species Sourcebook", "name": "Superior Ambition", "text": "When you spend Determination, you may add 3 Threat to gain two benefits from spending Determination, instead of 1."},
    {"species": "Klowahkan", "source": "Species Sourcebook", "name": "Epicurean", "text": "Your sense of smell and taste are highly acute. You can detect things by smell and taste that would not be obvious to creatures of other species, and any task roll you attempt which involves your sense of smell or taste is reduced by 2, to a minimum of 0. Furthermore, if you ever suffer Stress from ingesting food other species might regard as toxic, reduce the amount of Stress suffered by 1, to a minimum of 0."},
    {"species": "Ktarian", "source": "Species Sourcebook", "name": "Deep Determination", "text": "Ktarians have a well-earned reputation for committing absolutely to their goals, and a single-minded determination to achieve success. Once per mission, when you succeed at a task where you could have spent a point of Determination, but you chose not to, you may spend 3 Momentum to gain a point of Determination."},
    {"species": "Kwejian", "source": "Species Sourcebook", "name": "Natural Balance", "text": "Kwejians are sensitive to the cycles and patterns of the natural world. A Kwejian character may select the Empathy talent (page 155 of the core rulebook). Further, whenever you attempt a task to intuit or understand the nature or behavior of an alien life-form, you may reroll 1d20."},
    {"species": "Kzinti", "source": "Species Sourcebook", "name": "Feline Predator", "text": "You have retractable claws on your fingertips, useful for hunting. Due to your claws, your unarmed attacks may inflict both Stun and Deadly Injuries. Further, your maximum Stress is increased by 2, and when you attempt a Fitness test, you may suffer 1 Stress to reroll 1d20."},
    {"species": "Lanthanite", "source": "Species Sourcebook", "name": "Lived Nearly Forever", "text": "You’ve lived a very long time, and learned a lot. Up to twice per adventure, you may declare you have an experience or expertise in a particular field; you gain an additional focus when you do this, which remains for the rest of the adventure."},
    {"species": "Lurian", "source": "Species Sourcebook", "name": "Resistant Anatomy", "text": "Lurians are known for having an extremely hardy constitution. Capable of taking a knife to one of their hearts and keep fighting, Lurians have evolved a physiology that rivals even the redundant anatomy of the Klingons. Lurians have Protection 1 against all attacks, which increases to 2 against Stun Attacks, and you may suffer 1 Stress to ignore any effects or traits caused by toxins, drugs, or poisons. Further, the first time in an adventure you’re Defeated, you may immediately recover from being Defeated, though you still have whatever Injury caused you to become Defeated."},
    {"species": "Medusan", "source": "Species Sourcebook", "name": "Sublime Mind, Hideous Form", "text": "You have no physical form, but your mind is powerful indeed. You have the Telepathy and Telepathic Projection talents (both on page 156 of the core rulebook). However, corporeal beings who see your form immediately suffer a Deadly 5 Injury with the Debilitating and Piercing qualities (intentionally exposing your form in order to do harm adds 1 Threat per creature that would be affected) unless they’re wearing a protective visor. Telepathic species count the Severity of this injury to 3. Injuries you suffer represent disruptions to your electromagnetic matrix. When living among other species, you are assumed to dwell within a containment pod, which must be carried around by another character."},
    {"species": "Nanokin", "source": "Species Sourcebook", "name": "Tiny Being in a Lifelike Android", "text": "While in your conveyance, you may act freely as if you were any other character. When you leave your conveyance, you cannot be seen with the naked eye, and attacks against you automatically fail. While away from your conveyance, it operates on autopilot, and it cannot attempt any action which requires a task roll with a Difficulty of 1 or higher."},
    {"species": "Nausicaan", "source": "Species Sourcebook", "name": "Brute Force", "text": "You are tall, strong, and have little patience for subtlety or nuance. When you attempt a melee attack or a Fitness-based task roll to break or force your way through an obstacle or other problem, you may reroll 1d20, and you score 1 bonus Momentum if the task succeeds. Bonus Momentum cannot be saved. You have +1 Protection against Stun Attacks."},
    {"species": "Ocampa", "source": "Species Sourcebook", "name": "Extraordinary Mind", "text": "Your mind can assimilate new information swiftly, allowing you to gain knowledge and understand techniques quickly. The first time each scene that you Obtain Information after succeeding at a task roll which used one of your focuses, that use of Obtain Information is free. In addition, you may purchase talents from the Esoteric Talents list on page 155 of the core rulebook."},
    {"species": "Osnullus", "source": "Species Sourcebook", "name": "Unreadable Face", "text": "While Osnullus can look at each other’s faces and tell what they are thinking, it is more difficult for other species to do so. This natural trait gives them an advantage when it comes to treachery and deceit. On any task to try to mislead or lie to a member of another species, the first bonus d20 is free."},
    {"species": "Pakled", "source": "Species Sourcebook", "name": "Straightforward", "text": "A Pakled gains +1 Protection against Stun Attacks, and their Maximum Stress is equal to their Fitness +3."},
    {"species": "Reman", "source": "Species Sourcebook", "name": "Born to the Dark", "text": "You are nocturnal and have keen night vision: you may ignore the effects of any trait relating to low light or darkness, but any penalties suffered from traits caused by bright light are increased as if those traits had +1 Potency. Your tolerance for extreme exertion means your maximum Stress is increased by 2. Finally, you may select the Telepathy and Telepathic Projection talents (both on page 156 of the core rulebook). As subjects of the Romulan Star Empire, Remans may also purchase Romulan species talents."},
    {"species": "Rigellian Chelon", "source": "Species Sourcebook", "name": "Atavistic Defenses", "text": "Your biology contains a number of physiological defense mechanisms inherited from your ancestral species. Your shell gives you Protection 1, and means you may ignore the negative effects of traits that represent dangerous radiation. Further, your beak and natural toxins mean that your unarmed attacks inflict Stun/Deadly 3 Injuries with the Debilitating quality."},
    {"species": "Rigellian Jelna", "source": "Species Sourcebook", "name": "Divergent Physiology", "text": "Your species’ physiology diverges in more ways than most species do. When creating the character, choose Endosex or Exosex, and gain the appropriate trait. You gain the following ability: ENDOSEX: Whenever you attempt a task using Insight or Reason, the first d20 you purchase is free, and you gain 1 bonus Momentum on a successful task. Bonus Momentum cannot be saved. EXOSEX: Whenever you attempt a task using Daring or Fitness, the first d20 you purchase is free, and you gain 1 bonus Momentum on a successful task. Bonus Momentum cannot be saved"},
    {"species": "Risian", "source": "Species Sourcebook", "name": "Clarity in Peace", "text": "Your demeanor and presence help others reach a clear-minded state where they can be at their best. When an ally spends Determination, and you are present in the scene, both you and that ally may immediately recover 2 Stress each."},
    {"species": "Saurian", "source": "Species Sourcebook", "name": "Superior Metabolism", "text": "Your biology allows you to process toxins at a much higher rate than other species. Whenever you are exposed to a toxic substance, you may immediately suffer 1 or more Stress to shrug off the effects quickly. Most common toxins can be shrugged off with 1 Stress, but the gamemaster may rule that especially potent toxins require more Stress. In addition, your natural claws mean that your Unarmed Strikes can inflict Stun or Deadly Injuries."},
    {"species": "Son’a", "source": "Species Sourcebook", "name": "At All Costs", "text": "Though a small power in the region, the Son’a have not become one of the dominant powers in the Briar Patch by engaging in half measures or pulling their punches. When you succeed at a Deadly Attack, you score 1 bonus Momentum. Bonus Momentum may not be saved."},
    {"species": "Talaxian", "source": "Species Sourcebook", "name": "Widely Traveled", "text": "Having traveled through space for most of your adult life, you’ve seen much and picked up esoteric knowledge and unusual skills along the way. Once per mission, when attempting a task for which none of your focuses apply, you may declare that you have an applicable focus. This remains for the rest of the adventure."},
    {"species": "Tamarian", "source": "Species Sourcebook", "name": "Sokath, His Eyes Uncovered", "text": "You derive wisdom and understanding from the lessons and stories of the past. When you make a reference to a previous use of one of your values, you may also add 1 Momentum to the group pool."},
    {"species": "Terran", "source": "Species Sourcebook", "name": "Accustomed to Violence", "text": "Violence is a routine part of your life, and you are constantly aware of the potential for it. Whenever an enemy makes a Deadly Attack against you, you may add 1 Threat to increase the Difficulty of the attack by 1. Further, whenever you spend Determination on a Deadly Attack, you do not have to add to Threat to make that attack. Finally, you always carry a dagger as part of your standard issue equipment."},
    {"species": "Vau N’Akat", "source": "Species Sourcebook", "name": "Neuroflux", "text": "Vau N’Akat have an innate psychokinetic capability which they refer to as neuroflux. You can use this ability to heal yourself more swiftly: you may recover 2 Stress at the start of any scene. Further, when healing Injuries you have suffered, count the Severity of the Injury as 2 lower than normal. You may directly interact with objects of Vau N’Akat technology using your neuroflux, without the need for any control interfaces; when you do this, your eyes and patterns across your skin glow."},
    {"species": "Vorta", "source": "Species Sourcebook", "name": "The Voice of the Founders", "text": "When you use the Direct or Assist major action to aid or command another servant of the Dominion (a Jem’Hadar, a Vorta of lower status, or a member of an allied state), you may roll 2d20 for your assist dice rather than 1d20 and apply both results. If you are captured, you may trigger a termination implant as a minor action, which kills you instantly. Whenever you die, you are replaced by your next clone at the start of the next mission."},
    {"species": "Xahean", "source": "Species Sourcebook", "name": "Camouflage Field", "text": "Using the Prepare minor action, you may suffer 1 Stress to camouflage yourself, becoming nearly invisible. You gain the Camouflaged trait. While camouflaged, tasks to detect or locate you increase in Difficulty accordingly, and you cannot be the target of an attack unless the attacker has a complication. found some other way to detect you. This ends when you make an attack or when you take another Prepare minor action to end the effect. This ability is taxing, and the amount of Stress suffered increases by 1 each time during the same scene it is used; this increase is cumulative."},
    {"species": "Xindi-Aquatic", "source": "Species Sourcebook", "name": "Aquatic", "text": "You can move freely and without hindrance through the water. You may ignore any traits or injuries caused by exposure to extremely cold aquatic conditions. However, when on land you are always considered to be Prone (core rulebook, page 288)."},
    {"species": "Xindi-Arboreal", "source": "Species Sourcebook", "name": "Calm Under Pressure", "text": "Your unwavering calm allows you to maintain a clear head in a crisis. Your maximum Stress is equal to your Control, rather than your Fitness. Whenever you are affected by a trait or effect which represents fear or panic, you may suffer 2 Stress to avoid that trait."},
    {"species": "Xindi-Insectoid", "source": "Species Sourcebook", "name": "Insectoid", "text": "Your exoskeleton gives you Protection 1, while your rapid metabolism means that you may reroll 1d20 on any task roll using Fitness."},
    {"species": "Xindi-Primate", "source": "Species Sourcebook", "name": "Adaptable and Talented", "text": "Xindi-Primates are well-known and respected for their ingenuity and drive to overcome challenges. Once per mission, when you attempt a task roll, select one of your focuses: on that task roll, and for the remainder of the mission, whenever you succeed at a task using that focus, you score 1 bonus Momentum. Bonus Momentum may not be saved."},
    {"species": "Xindi-Reptilians", "source": "Species Sourcebook", "name": "Durable Physiology", "text": "Xindi- Reptilians are tough, and cannot easily be stopped by attacks intended to subdue or incapacitate. Nothing short of deadly force can deter you. You have 1 Protection, which increases to 3 against Stun Attacks."},
    {"species": "Yridian", "source": "Species Sourcebook", "name": "Eidetic Memory", "text": "Yridians have an extraordinary ability to process, retain, and recall information. You may spend 1 Momentum (and a major action if in combat) attempting an Insight + Science task with a Difficulty of 0 to recall some event which you witnessed in the past; Momentum spent may be used to Obtain Information to gain new insights from this recollection."},
    {"species": "Zakdorn", "source": "Species Sourcebook", "name": "Several Moves Ahead", "text": "Zakdorn are reputed to have the finest strategic minds, and they can analyze complex situations and predict their outcomes with startling accuracy. Once per scene, when you create a trait representing a plan of action or a strategy, you may spend 1 additional Momentum to either increase the Potency of that trait by 1, or to create a second copy of that trait to grant to an ally you are in communication with."}
];
